name: Check Markdown links

on:
  pull_request:

inputs:
  DOC_DIR:
    description: "default directory path from project root"
    required: false
    default: .
  QUIET_MODE:
    description: "default to only show errors in output."
    required: false
    default: yes
  VERBOSE_MODE:
    description: "default to show detailed HTTP status for checked links."
    required: false
    default: yes
  CONFIG_FILE:
    description: "default config file."
    required: false
    default: .github/md-link-check.json
  BRANCH:
    description: "default branch"
    required: false
    default: main

jobs:
  markdown-link-check:
    runs-on: ["self-hosted", "Linux", "X64", "generic"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Check links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: ${{ inputs.QUIET_MODE }}
          use-verbose-mode: ${{ inputs.VERBOSE_MODE }}
          check-modified-files-only: yes
          base-branch: ${{ inputs.BRANCH }}
          config-file: ${{ inputs.CONFIG_FILE }}
          folder-path: ${{ inputs.DOC_DIR }}
