name: Check for lint/build errors

on:
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ["self-hosted", "Linux", "X64", "generic"]
    steps:
      - uses: actions/checkout@v3
      - name: Read .nvmrc
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm
      - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/

      - name: npm install, lint
        run: |
          npm ci
          npm run lint
          npm run typecheck
  build:
    runs-on: ["self-hosted", "Linux", "X64", "generic"]
    steps:
      - uses: actions/checkout@v3
      - name: Read .nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm
      - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/

      - name: npm install, build
        run: |
          npm ci
          npm run build
