---
name: Check for lint/build errors

on:
  push: {}
  pull_request: {}

jobs:
  lint:
    name: Lint Code Base
    runs-on: [self-hosted, linux, X64, generic]
    # the enviroment to deploy to / use secrets from
    environment: no-secret
    # modify the default permissions of the GITHUB_TOKEN, so as to only allow least priveleges
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Lint
        uses: ConsenSys/docs-gha/lint@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
