name: Release to GitHub
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ["self-hosted", "Linux", "X64", "generic"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Read .nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm
      - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm run ci

      - name: Build package
        run: npm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HUSKY: 0 # disable hooks for release
        run: npx semantic-release
